#
# MIT License
#
# Copyright(c) 2011-2020 The Maintainers of Nanvix
#
# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:
#
# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.
#

# Compiler Options
ifneq ($(LIBLWIP),)
CFLAGS += -I $(INCDIR)/posix
endif

# Whole Libraries
LIBS := -Wl,--whole-archive
ifneq ($(LIBHAL),)
LIBS += $(LIBDIR)/$(LIBHAL)
endif
ifneq ($(LIBKERNEL),)
LIBS += $(LIBDIR)/$(LIBKERNEL)
endif

# Dependent No Whole Libraries
LIBS += -Wl,--no-whole-archive
LIBS += $(MODULES)

# Interdependent No Whole Libraries
LIBS += -Wl,--start-group
ifneq ($(LIBRUNTIME),)
LIBS += $(LIBDIR)/$(LIBRUNTIME)
endif
ifneq ($(LIBC),)
LIBS += $(LIBDIR)/$(LIBC)
endif
ifneq ($(LIBMPI),)
LIBS += $(LIBDIR)/$(LIBMPI)
endif
ifneq ($(LIBNANVIX),)
LIBS += $(LIBDIR)/$(LIBNANVIX)
endif
LIBS += -Wl,--end-group

# Independent No Whole Libraries
LIBS += -Wl,--no-whole-archive
ifneq ($(LIBLWIP),)
LIBS += $(LIBDIR)/$(LIBLWIP)
endif
LIBS += $(LIBDIR)/$(BARELIB)

ifeq ($(TARGET),mppa256)
ifeq ($(OBJ_SUFFIX),k1bio)
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/k1bio/le/bare/mOS/crti.o
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/k1bio/le/bare/mOS/crtbegin.o
LIBS += $(TOOLCHAIN_DIR)/k1-elf/lib/k1bio/le/bare/mOS/crt0.o
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/k1bio/le/bare/mOS/crtend.o
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/k1bio/le/bare/mOS/crtn.o
else
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/mOS/crti.o
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/mOS/crtbegin.o
LIBS += $(TOOLCHAIN_DIR)/k1-elf/lib/mOS/crt0.o
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/mOS/crtend.o
LIBS += $(TOOLCHAIN_DIR)/lib/gcc/k1-elf/4.9.4/mOS/crtn.o
endif
endif

LIBS += $(THEIR_LIBS)

# Linker Options
ifeq ($(TARGET),unix64)
LINKER_SCRIPT=
else
LINKER_SCRIPT = -L $(LINKERDIR)/ -T link.ld
endif
